# Generated by Django 5.2.6 on 2026-04-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activo_en_plataforma',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='puede_comentar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='puede_descargar_pdfs',
            field=models.BooleanField(default=False),
        ),
    ]
