# Generated by Django 5.2.6 on 2026-04-19 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelCorderito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Nivel de Corderitos',
                'verbose_name_plural': 'Niveles de Corderitos',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='contenido',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterField(
            model_name='contenido',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='contenidos.categoria'),
        ),
        migrations.CreateModel(
            name='TemaCorderito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='contenidos.nivelcorderito')),
            ],
            options={
                'verbose_name': 'Tema de Corderitos',
                'verbose_name_plural': 'Temas de Corderitos',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='contenido',
            name='tema',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contenido', to='contenidos.temacorderito'),
        ),
    ]
