# Generated by Django 5.2.6 on 2026-04-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0003_calendariodelmes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendariodelmes',
            name='imagen',
            field=models.CharField(max_length=255),
        ),
    ]
